### ISSUE TITLE
missing sentence_transformers

### ISSUE THREAD

**Issue by NagasadaSanshiro** [tinyzqh/TalkBotGPT#1]
cannot find module sentence_transformers in the base_prompt.py

**Comment by tinyzqh** [comment]
pip install -U sentence-transformers

**Comment by tinyzqh** [comment]
and you can download the model weight ref: https://huggingface.co/shibing624/text2vec-base-chinese

```python
SentenceModel('shibing624/text2vec-base-chinese')
```

**Comment by tinyzqh** [comment]
This bug has been fixed. can ref: https://github.com/tinyzqh/TalkBotGPT/commit/f6975d51d9ed6b56f8931a2a790d8f746cb48258#
